#ifndef SERIAL_PROTOCOL_H
#define SERIAL_PROTOCOL_H

const String ARDUINO_ACK_SUCCESS = "ACK_SUCCESS";
const String ARDUINO_ACK_FAILURE = "ACK_FAILURE";

const String ARDUINO_COMMAND_SCAN = "CMD_SCAN";
const String ARDUINO_COMMAND_WAVE = "CMD_WAVE";
const String ARDUINO_COMMAND_DANCE = "CMD_DANCE"; 
const String ARDUINO_COMMAND_BUZZ = "CMD_BUZZ";
const String ARDUINO_COMMAND_BUZZ_LONG = "CMD_BUZZ_LONG";

const String ARDUINO_NOTIFICATION_BUTTON = "NTF_BUTTON";

#endif // SERIAL_PROTOCOL_H
